name: Security Scan

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]
  schedule:
    # Run daily at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  vulnerability-scan:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write
      issues: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Vuln Agent scan
        uses: ./
        with:
          path: '.'
          llm-provider: 'gemini-2.5-flash'
          format: 'markdown'
          extensions: '.js,.ts,.jsx,.tsx,.py,.go'
          ignore: 'node_modules,.git,dist,build,.next,coverage'
          fail-on-vulnerabilities: 'false'
          upload-results: 'true'
          comment-on-pr: 'true'
        env:
          GEMINI_2_5_FLASH_API_KEY: ${{ secrets.GEMINI_2_5_FLASH_API_KEY }}

      - name: Display scan summary
        if: always()
        run: |
          echo "Vulnerability scan completed"
          echo "Found vulnerabilities: ${{ steps.scan.outputs.vulnerability-count }}"
